### ISSUE TITLE
Analyse pull request of a certain label

### ISSUE THREAD

**Issue by williammizuta** [elo7/github-notifications#4]
I would like to write a rule that should be applied for pull requests that have a certain label:

```
[
  {
    create: 5,
    update: 2
  },
  {
    label: bugs,
    create: 3,
    update: 1
  }
]
```

When a group of rules doesn't have a label defined, they should be applied to all repository pull requests.

**Comment by leocwolter** [comment]
Maybe the rules group should have conditions and actions declared separately. E.g.:
```
[
  {
     conditions: {
        create: 5,
        update: 3
    }
    actions: {
         email: true,
         label: 'OLD'
     }
 }
]
```
This would send an email and add the label
`OLD` for each PR older than 5 days and that wasn't updated for 3 days
